version: '2'

services:
  db:
    image: mongo:3.4
    networks:
      - ntw
    volumes:
      - db:/root/volumes/cpps_db
      - db_data:/data/db
    restart: always
  app:
    build: .
    image: cpps
    depends_on:
      - db
    ports:
      - "8000:8002"
      - "3000:3000"
    networks:
      - ntw
    volumes:
      - app:/home/volumes/cpps_app
      - ./:/root/src/
    command: tail -f /dev/null

networks:
  ntw:

volumes:
  db_data:
  db:
  app:
